config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resources :templates do
      resources :signature_requests
    end
  end

  root 'welcome#index'

  resources :hellosign do
  	collection do
  		post 'callbacks'
  	end
  end

end

app/models/signature_request.rb
class SignatureRequest < ActiveRecord::Base
  belongs_to :template

  def send_request(template_id)
    @template = Template.find(template_id)

    client = HelloSign::Client.new :api_key => ENV['HELLOSIGN_API_KEY']
      request = client.create_embedded_unclaimed_draft_with_template(
        :test_mode => 1,
        :client_id => ENV['HELLOSIGN_CLIENT_ID'],
        :template_id => '51d61b1c0b9a7a73b04e245587aa7a59875bd6d7',
        :requester_email_address => email,
        :signing_redirect_url => 'https://hellosign-templates-example.herokuapp.com',
        :requesting_redirect_url => 'https://hellosign-templates-example.herokuapp.com',
        :is_for_embedded_signing => 1,
        :metadata => {
            :House => 'Griffyndor'
        },
        :signers => [
            {
              :email_address => email,
              :name => name,
              :role => 'Test Role'
            },
            {
              :email_address => 'Chad@velocis.us',
              :name => 'Chad H',
              :role => 'Test Role 2'
            }
        ],
        :ccs => [
          {
            :email_address => 'chadheinen13@yahoo.com',
            :role => '0est CC Role'
          }
        ]
    )

    self.claim_url = request.data['claim_url']
    self.signing_redirect = request.data['signing_redirect_url']
    self.hellosign_signature_id = request.data['signature_request_id']
  end

end

app/controllers/signature_requests_controller.rb
class SignatureRequestsController < ApplicationController
  before_action :set_signature_request, only: [:show, :edit, :update, :destroy]
  before_action :set_template

  # GET /signature_requests
  # GET /signature_requests.json
  def index
    @signature_requests = @template.signature_requests
  end

  # GET /signature_requests/1
  # GET /signature_requests/1.json
  def show
  end

  # GET /signature_requests/new
  def new
    @signature_request = @template.signature_requests.new
  end

  # GET /signature_requests/1/edit
  def edit
  end

  # POST /signature_requests
  # POST /signature_requests.json
  def create
    @signature_request = @template.signature_requests.new(signature_request_params)
    respond_to do |format|
      if @signature_request.save
        format.html { redirect_to user_template_signature_requests_path, notice: 'Signature request was successfully created.' }
        format.json { render :show, status: :created, location: @signature_request }
      else
        format.html { render :new }
        format.json { render json: @signature_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signature_requests/1
  # PATCH/PUT /signature_requests/1.json
  def update
    respond_to do |format|
      if @signature_request.update(signature_request_params)
        format.html { redirect_to [current_user, @template, @signature_request], notice: 'Signature request was successfully updated.' }
        format.json { render :show, status: :ok, location: @signature_request }
      else
        format.html { render :edit }
        format.json { render json: @signature_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signature_requests/1
  # DELETE /signature_requests/1.json
  def destroy
    @signature_request.destroy
    respond_to do |format|
      format.html { redirect_to user_template_signature_requests_path, notice: 'Signature request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signature_request
      @signature_request = SignatureRequest.find(params[:id])
    end

    def set_template
      @template = Template.find(params[:template_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signature_request_params
      params.require(:signature_request).permit(:template_id, :email, :name, :claim_url,:signing_redirect, :hellosign_signature_id)
    end
end

app/helpers/signature_requests_helper.rb
module SignatureRequestsHelper
end

app/views/signature_requests/_form.html.erb
<%= form_for([current_user, @template, @signature_request], html: {class: 'signup_form well template_form col-md-4 col-md-offset-4'}) do |f| %>
  <% if @signature_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signature_request.errors.count, "error") %> prohibited this signature_request from being saved:</h2>

      <ul>
      <% @signature_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label @template.title %><br>
    <%= hidden_field_tag :template_id , @template.id %>
  </div>

  <br>

  <div class="field">
    <%= f.label "What is the recipient's Name?" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "What is the recipient's email?" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Signature Request', class: 'btn btn-primary' %>
  </div>

  <br>
  <%= link_to 'Back', user_template_signature_requests_path(current_user, @template) %>
<% end %>

app/views/signature_requests/edit.html.erb
<h1>Editing Signature Request</h1>

<%= render 'form' %>

<%= link_to 'Show', user_template_signature_request_path(current_user, params[:template_id], @signature_request) %> |
<%= link_to 'Back', user_template_signature_requests_path %>

app/views/signature_requests/index.html.erb
<p id="notice"><%= notice %></p>

<div class='container fluid buttons'>

<br>

<%= link_to '< Back to Templates', user_templates_path, class: 'btn btn-md btn-primary new_template col-md-2 col-md-offset-0' %>

<br><br>

<h1>Signature Requests for <%= @template.title %></h1>

<h5 class='well'>
  These are Signature Requests that have been created in your Rails application. They create the data for your database tables and form your API calls that can be found in the Signature Request Model.

  <br><br>

  Click "Send Signature Request" to create and send a signature request using the Rails information as the params for the HelloSign API.

  <br><br>

  ** You will NOT be able to send a Signature Request if you have not yet created your Template on HelloSign. That is different than created it on the rails app. **
</h5>

<br>

<table class='table'>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Recipient Name</th>
      <th>Recipient Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signature_requests.each do |signature_request| %>
      <tr>
        <td><%= @template.subject %></td>
        <td><%= signature_request.name %></td>
        <td><%= signature_request.email %></td>
        <td><%= link_to 'View', user_template_signature_request_path(current_user, params[:template_id],signature_request) %></td>
        <td><%= link_to 'Edit', edit_user_template_signature_request_path(current_user, params[:template_id], signature_request) %></td>
        <td><%= link_to 'Delete', user_template_signature_request_path(current_user, params[:template_id], signature_request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if @template.hellosign_id.nil? %>
          <td><%= link_to 'Create your Template on HelloSign', user_template_path(current_user, @template), class: 'btn btn-md btn-primary' %></td>
        <% else %>
          <td><%= link_to 'Send Signature Request', hellosign_path(signature_request, {template_id: params[:template_id]}), class: 'btn btn-md btn-primary' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Signature request', new_user_template_signature_request_path, class: 'btn btn-md btn-primary new_template col-md-12 col-md-offset-0' %>

</div>

app/views/signature_requests/new.html.erb
<body class='blue_form'>

<h1>New Signature Request</h1>

<%= render 'form' %>

</body>

app/views/signature_requests/show.html.erb
<div class='container fluid buttons'>

<br><br><br>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Template:</strong>
    <%= @signature_request.template.title %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @signature_request.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @signature_request.name %>
  </p>

  <div class='buttons'>
    <%= link_to 'Preview & Send Signature Request', new_hellosign_path(@signature_request), class: 'btn btn-md btn-primary' %> |
    <%= link_to 'Edit', edit_user_template_signature_request_path(current_user, params[:template_id], @signature_request) %> |
    <%= link_to 'Back', user_template_signature_requests_path %>
  </div>

</div>