config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resources :templates do
      resources :signature_requests
    end
  end

  root 'welcome#index'

  resources :hellosign do
  	collection do
  		post 'callbacks'
  	end
  end

end

app/views/templates/_form.html.erb
<%= form_for([current_user, @template], html: {class: 'signup_form well template_form col-md-4 col-md-offset-4'}, multipart: true) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit 'Start Template', class: 'btn btn-primary' %>
  </div>

<br>
<%= link_to 'Back', user_templates_path %>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/hellosign.js.erb
$('#div_id').html("<%= render :partial => 'show.html.erb' %>");

app/views/templates/index.html.erb
<div class='container fluid buttons'>

<br>

  <p id="notice"><%= notice %></p>

  <h1>Your Templates</h1>

<h5 class='well'>
  These are Templates that have been created in your Rails application. They create the data for your database tables and form your API calls that can be found in the Template Model.

  <br><br>

  Click "view" in order to create the Template on HelloSign.
</h5>

  <table class='table'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Subject</th>
        <th>Message</th>
        <th>File</th>
      </tr>
    </thead>

    <tbody>
      <% @templates.each do |template| %>
        <tr>
          <td><%= template.title %></td>
          <td><%= template.subject %></td>
          <td><%= template.message %></td>
          <td><%= template.file %></td>
          <td><%= link_to 'View', user_template_path(current_user, template) %></td>
          <td><%= link_to 'Delete', user_template_path(current_user, template), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% if template.hellosign_id.nil? %>
            <td><%= link_to 'Create your Template on HelloSign', user_template_path(current_user, template), class: 'btn btn-md btn-primary' %></td>
          <% else %>
            <td><%= link_to 'Edit your Template on HelloSign', user_template_path(current_user, @template), class: 'btn btn-md btn-primary' %></td>
            <td><%= link_to 'View Signature Requests', user_template_signature_requests_path(current_user, template), class: 'btn btn-md btn-primary' %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

    <%= link_to 'New Template', new_user_template_path, class: 'btn btn-md btn-primary new_template col-md-12 col-md-offset-0' %>

</div>

app/views/templates/new.html.erb
<body class='blue_form'>

	<h1>New Template</h1>

	<%= render 'form' %>

</body>

app/views/templates/show.html.erb
<div class='container'>

  <p id="notice"><%= notice %></p>

<br>

<h5 class='well'>
  This is a Template that has been created in your Rails application.

  <br><br>

  Use the "Create Template on HelloSign" button to Create your Template using your Rails data and the HelloSign API"

  Use the "Edit this Template on HelloSign" button to Edit your Template using the HelloSign API.

  <br><br>

  You can create requests in the Rails application (not HelloSign) by clicking "Create a Request with this Template", or you can view all existing requests that were made with this template by clicking "View All Signature Requests"
</h5>

  <p>
    <strong>Template ID:</strong>
    <%= @template.id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @template.title %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= @template.subject %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= @template.message %>
  </p>

  <p>
    <strong>Hellosign Template ID:</strong>
    <%= @template.hellosign_id %>
  </p>

  <p>
    <strong>Hellosign Edit URL</strong>
    <%= @template.edit_url %>
  </p>

  <br>

  <div class='buttons'>

  <% if @template.hellosign_id.nil? %>
    <%= link_to 'Create Template on HelloSign', new_hellosign_path(@template), class: 'btn btn-md btn-primary' %>
  <% else %>
    <%= link_to 'Edit this Template on HelloSign', edit_hellosign_path(@template), class: 'btn btn-md btn-primary' %> |
    <%= link_to 'Create a Request with this Template', new_user_template_signature_request_path(current_user, @template), class: 'btn btn-md btn-primary' %> |
    <%= link_to 'View All Signature Requests', user_template_signature_requests_path(current_user, @template), class: 'btn btn-md btn-primary' %>
  <% end %>

    <br><br>
    <%= link_to 'Back to Templates List', user_templates_path %>
  </div>

</div>