config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resources :templates do
      resources :signature_requests
    end
  end

  root 'welcome#index'

  resources :hellosign do
  	collection do
  		post 'callbacks'
  	end
  end

end

app/controllers/hellosign_controller.rb
class HellosignController < ApplicationController
skip_before_action :verify_authenticity_token, only: [:callbacks]

  def callbacks
    respond_to do |format|
      format.json { render json: 'Hello API Event Received', status: 200 }
    end
  end

  # New Template
  def new
    @template = Template.find(params[:format])
    @template.create_embedded_template
  end

  # Send Signature Request
  def show
    @signature_request = SignatureRequest.find(params[:id])
    @signature_request.send_request(params[:template_id])
  end

  # Edit Template
  def edit
    @template = Template.find(params[:id])
    @template.edit_embedded_template
  end

  private

end

app/views/hellosign/edit.html.erb
<body class='blue_form'>

<script type="text/javascript" src="//s3.amazonaws.com/cdn.hellofax.com/js/embedded.js"></script>

<script type="text/javascript">
  HelloSign.init("<%= ENV['HELLOSIGN_CLIENT_ID'] %>");
  HelloSign.open({ url: '<%= @template.edit_url %>' });
</script>

<br><br><br><br><br><br>

<h1>
<%= link_to 'Back to Template', @template, class: 'back_to_templates' %>
</h1>

</body>

app/views/hellosign/new.html.erb
<body class='blue_form'>

<script type="text/javascript" src="//s3.amazonaws.com/cdn.hellofax.com/js/embedded.js"></script>

<script type="text/javascript">
  HelloSign.init("<%= ENV['HELLOSIGN_CLIENT_ID'] %>");
  HelloSign.open({ url: '<%= @template.edit_url %>' });
</script>

<br><br><br><br><br><br>

<h1>
<%= link_to 'Back to the Template Page', template_path(@template), class: 'back_to_templates' %>
</h1>

</body>

app/views/hellosign/show.html.erb
<body class='blue_form'>

<script type="text/javascript" src="//s3.amazonaws.com/cdn.hellofax.com/js/embedded.js"></script>

<script type="text/javascript">
  HelloSign.init("<%= ENV['HELLOSIGN_CLIENT_ID'] %>");
  HelloSign.open({ url: '<%= @signature_request.claim_url %>' });
</script>

<br><br><br><br><br><br>

<h1>
<%= link_to 'This will take you back to your templates page.', '/templates', class: 'back_to_templates' %>
</h1>

</body>